graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

#endpoint configuration for the graphical interface
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.11.11

#h2 in memory db configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: su
    password: admin
    driverClassName: org.h2.Driver
